# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\x12\x06orders\"L\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07product\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x16\n\x0epayment_status\x18\x04 \x01(\x08\".\n\x0b\x43reateOrder\x12\x0f\n\x07product\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\"+\n\x0bUpdateOrder\x12\x1c\n\x05order\x18\x01 \x01(\x0b\x32\r.orders.Order\"!\n\x13GetOrderByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"4\n\x14GetOrderByIdResponse\x12\x1c\n\x05order\x18\x01 \x01(\x0b\x32\r.orders.Order\"8\n\x12\x43reateOrderRequest\x12\"\n\x05order\x18\x01 \x01(\x0b\x32\x13.orders.CreateOrder\"3\n\x13\x43reateOrderResponse\x12\x1c\n\x05order\x18\x01 \x01(\x0b\x32\r.orders.Order\"2\n\x12UpdateOrderRequest\x12\x1c\n\x05order\x18\x01 \x01(\x0b\x32\r.orders.Order\"3\n\x13UpdateOrderResponse\x12\x1c\n\x05order\x18\x01 \x01(\x0b\x32\r.orders.Order2\xef\x01\n\x0cOrderService\x12K\n\x0cGetOrderById\x12\x1b.orders.GetOrderByIdRequest\x1a\x1c.orders.GetOrderByIdResponse\"\x00\x12H\n\x0b\x43reateOrder\x12\x1a.orders.CreateOrderRequest\x1a\x1b.orders.CreateOrderResponse\"\x00\x12H\n\x0bUpdateOrder\x12\x1a.orders.UpdateOrderRequest\x1a\x1b.orders.UpdateOrderResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=24
  _globals['_ORDER']._serialized_end=100
  _globals['_CREATEORDER']._serialized_start=102
  _globals['_CREATEORDER']._serialized_end=148
  _globals['_UPDATEORDER']._serialized_start=150
  _globals['_UPDATEORDER']._serialized_end=193
  _globals['_GETORDERBYIDREQUEST']._serialized_start=195
  _globals['_GETORDERBYIDREQUEST']._serialized_end=228
  _globals['_GETORDERBYIDRESPONSE']._serialized_start=230
  _globals['_GETORDERBYIDRESPONSE']._serialized_end=282
  _globals['_CREATEORDERREQUEST']._serialized_start=284
  _globals['_CREATEORDERREQUEST']._serialized_end=340
  _globals['_CREATEORDERRESPONSE']._serialized_start=342
  _globals['_CREATEORDERRESPONSE']._serialized_end=393
  _globals['_UPDATEORDERREQUEST']._serialized_start=395
  _globals['_UPDATEORDERREQUEST']._serialized_end=445
  _globals['_UPDATEORDERRESPONSE']._serialized_start=447
  _globals['_UPDATEORDERRESPONSE']._serialized_end=498
  _globals['_ORDERSERVICE']._serialized_start=501
  _globals['_ORDERSERVICE']._serialized_end=740
# @@protoc_insertion_point(module_scope)
