# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payments.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epayments.proto\x12\x08payments\"9\n\x07Payment\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\x12\x12\n\npayment_id\x18\x03 \x01(\t\")\n\x15ProcessPaymentRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\"<\n\x16ProcessPaymentResponse\x12\"\n\x07payment\x18\x01 \x01(\x0b\x32\x11.payments.Payment\".\n\x1aGetPaymentByOrderIdRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\"A\n\x1bGetPaymentByOrderIdResponse\x12\"\n\x07payment\x18\x01 \x01(\x0b\x32\x11.payments.Payment2\xcd\x01\n\x0ePaymentService\x12U\n\x0eProcessPayment\x12\x1f.payments.ProcessPaymentRequest\x1a .payments.ProcessPaymentResponse\"\x00\x12\x64\n\x13GetPaymentByOrderId\x12$.payments.GetPaymentByOrderIdRequest\x1a%.payments.GetPaymentByOrderIdResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payments_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENT']._serialized_start=28
  _globals['_PAYMENT']._serialized_end=85
  _globals['_PROCESSPAYMENTREQUEST']._serialized_start=87
  _globals['_PROCESSPAYMENTREQUEST']._serialized_end=128
  _globals['_PROCESSPAYMENTRESPONSE']._serialized_start=130
  _globals['_PROCESSPAYMENTRESPONSE']._serialized_end=190
  _globals['_GETPAYMENTBYORDERIDREQUEST']._serialized_start=192
  _globals['_GETPAYMENTBYORDERIDREQUEST']._serialized_end=238
  _globals['_GETPAYMENTBYORDERIDRESPONSE']._serialized_start=240
  _globals['_GETPAYMENTBYORDERIDRESPONSE']._serialized_end=305
  _globals['_PAYMENTSERVICE']._serialized_start=308
  _globals['_PAYMENTSERVICE']._serialized_end=513
# @@protoc_insertion_point(module_scope)
