# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\")\n\nCreateUser\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"7\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\x11\n\x0fGetUsersRequest\"6\n\x10GetUsersResponse\x12\"\n\x05users\x18\x01 \x03(\x0b\x32\x13.users.UserResponse\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"8\n\x13GetUserByIdResponse\x12!\n\x04user\x18\x01 \x01(\x0b\x32\x13.users.UserResponse2\x94\x01\n\x0bUserService\x12=\n\x08GetUsers\x12\x16.users.GetUsersRequest\x1a\x17.users.GetUsersResponse\"\x00\x12\x46\n\x0bGetUserById\x12\x19.users.GetUserByIdRequest\x1a\x1a.users.GetUserByIdResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEUSER']._serialized_start=22
  _globals['_CREATEUSER']._serialized_end=63
  _globals['_USERRESPONSE']._serialized_start=65
  _globals['_USERRESPONSE']._serialized_end=120
  _globals['_GETUSERSREQUEST']._serialized_start=122
  _globals['_GETUSERSREQUEST']._serialized_end=139
  _globals['_GETUSERSRESPONSE']._serialized_start=141
  _globals['_GETUSERSRESPONSE']._serialized_end=195
  _globals['_GETUSERBYIDREQUEST']._serialized_start=197
  _globals['_GETUSERBYIDREQUEST']._serialized_end=229
  _globals['_GETUSERBYIDRESPONSE']._serialized_start=231
  _globals['_GETUSERBYIDRESPONSE']._serialized_end=287
  _globals['_USERSERVICE']._serialized_start=290
  _globals['_USERSERVICE']._serialized_end=438
# @@protoc_insertion_point(module_scope)
